-- COMANDOS SQL SE DIVIDEM EM DUAS LINGUAGENS
-- -----------------------------------------------------
-- DDL (Data Definition Languagem)
-- => Comandos de definiçãio de banco de dados
-- Ex: CREATE DATABASE NAME 
-- DROP DATABASE NAME
-- CREATE TABLE NAME (COLUNAS)
-- DROP TABLE NAME 	

-- ----------------------------------------------------
-- DML (Data Manipulation Language)
-- => Comandos de manipulação de dados
-- EX: SELECT COLUNAS FROM TABELA
-- INSERT INTO TABELA (COLUNAS) VALUES (VALORES)
-- DELETE FROM TABELA
-- UPDATE COLUNAS FROM TABELA